-- UNION ELIMINA LINHAS REPETIDAS AUTOMATICAMENTE
-- UNION ALL não aplica distinct sobre o resultado

USE SUCOS_VENDAS;


SELECT DISTINCT BAIRRO FROM TABELA_DE_CLIENTES;
--12 bairros clientes

SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES;
--4 bairros clientes

SELECT DISTINCT BAIRRO FROM TABELA_DE_CLIENTES
UNION
SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES;

SELECT DISTINCT BAIRRO FROM TABELA_DE_CLIENTES
UNION ALL
SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES;


SELECT DISTINCT BAIRRO, 'CLIENTE' AS ORIGEM FROM TABELA_DE_CLIENTES
UNION ALL
SELECT DISTINCT BAIRRO, 'FORNECEDOR' AS ORIGEM FROM TABELA_DE_VENDEDORES;
--identificando de qual tabela os dados vem

SELECT DISTINCT BAIRRO, 'CLIENTE' AS ORIGEM FROM TABELA_DE_CLIENTES
UNION 
SELECT DISTINCT BAIRRO, 'FORNECEDOR' AS ORIGEM FROM TABELA_DE_VENDEDORES;
--devido a adção do coluna origem, o UNION não consegue fazer o DISTINCT
