USE LAB_COMEX;

SELECT * FROM CLIENTES;

SELECT NOME, CIDADE, UF FROM CLIENTES;

SELECT NOME, CPF, BAIRRO FROM CLIENTES;

SELECT CPF AS [CPF do CLiente], NOME AS [Nome do Cliente] FROM CLIENTES;

SELECT TB_CLIENTES.NOME, TB_CLIENTES.BAIRRO FROM CLIENTES TB_CLIENTES;