USE LAB_COMEX;

SELECT * FROM CLIENTES WHERE COD_CLIENTE < 4;

SELECT NOME, UF FROM CLIENTES WHERE DATA_DE_NASCIMENTO > '2000-01-01';

SELECT * FROM  CLIENTES WHERE UF IN ('RJ', 'SP', 'MG');

SELECT * FROM CLIENTES WHERE NOME LIKE '%GUST%';