/**
CREATE DATABASE LAB_COMEX;
**/

CREATE DATABASE LAB_COMEX
ON (NAME = 'LAB_COMEX.DAT',
	FILENAME = 'C:\TEMP2\LAB_COMEX.MDF',
	SIZE = 10MB,
	MAXSIZE = 50MB,
	FILEGROWTH = 5MB)

LOG ON
	(NAME = 'LAB_COMEX.LOG',
	FILENAME = 'C:\TEMP2\LAB_COMEX.LDF',
	SIZE = 10MB,
	MAXSIZE = 50MB,
	FILEGROWTH = 5MB);

/**
CREATE DATABASE [SUCOS_VENDAS_06]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SUCOS_VENDAS_06', FILENAME = N'C:\TEMP2\SUCOS_VENDAS_06.mdf' , SIZE = 10240KB , MAXSIZE = 25600KB , FILEGROWTH = 10240KB )
 LOG ON 
( NAME = N'SUCOS_VENDAS_06_log', FILENAME = N'C:\TEMP2\SUCOS_VENDAS_06_log.ldf' , SIZE = 10240KB , MAXSIZE = 25600KB , FILEGROWTH = 5120KB )
**/