CREATE VIEW NOME_VALOR AS
SELECT P.NOME,
	P.DESCRICAO,
	P.QUANTIDADE_DISPONIVEL,
	IP.VALOR,
	IP.PRECO_UNITARIO
FROM PRODUTO P
INNER JOIN ITEM_PEDIDO IP
	ON P.COD_PRODUTO = IP.COD_PRODUTO
--

USE COMEX;

SELECT *
FROM NOME_VALOR;
--