USE COMEX;

-- Mostra todos os dados
SELECT C.NOME,
		C.EMAIL,
		P.VALOR_TOTAL,
		P.DESCONTO,
		IP.PRECO_UNITARIO,
		IP.VALOR,
		PROD.NOME,
		PROD.QUANTIDADE_DISPONIVEL,
		CAT.NOME
FROM CLIENTE C
INNER JOIN PEDIDO P
	ON C.COD_CLIENTE = P.COD_CLIENTE
INNER JOIN ITEM_PEDIDO IP
	ON P.COD_PEDIDO = IP.COD_PEDIDO
INNER JOIN PRODUTO PROD
	ON IP.COD_PRODUTO = PROD.COD_PRODUTO
INNER JOIN PRODUTO_CATEGORIA PC
	ON PROD.COD_PRODUTO = PC.COD_PRODUTO
INNER JOIN CATEGORIA CAT
	ON PC.COD_CATEGORIA = CAT.COD_CATEGORIA;
--

-- Mostra todos os produtos com desconto
SELECT C.NOME,
		C.EMAIL,
		P.VALOR_TOTAL,
		P.DESCONTO,
		IP.PRECO_UNITARIO,
		IP.VALOR,
		PROD.NOME,
		PROD.QUANTIDADE_DISPONIVEL,
		CAT.NOME
FROM CLIENTE C
INNER JOIN PEDIDO P
	ON C.COD_CLIENTE = P.COD_CLIENTE
INNER JOIN ITEM_PEDIDO IP
	ON P.COD_PEDIDO = IP.COD_PEDIDO
INNER JOIN PRODUTO PROD
	ON IP.COD_PRODUTO = PROD.COD_PRODUTO
INNER JOIN PRODUTO_CATEGORIA PC
	ON PROD.COD_PRODUTO = PC.COD_PRODUTO
INNER JOIN CATEGORIA CAT
	ON PC.COD_CATEGORIA = CAT.COD_CATEGORIA
WHERE P.DESCONTO > 0;
--

-- Mostra todos os produtos indisponiveis
SELECT C.NOME,
		C.EMAIL,
		P.VALOR_TOTAL,
		P.DESCONTO,
		IP.PRECO_UNITARIO,
		IP.VALOR,
		PROD.NOME,
		PROD.QUANTIDADE_DISPONIVEL,
		CAT.NOME
FROM CLIENTE C
INNER JOIN PEDIDO P
	ON C.COD_CLIENTE = P.COD_CLIENTE
INNER JOIN ITEM_PEDIDO IP
	ON P.COD_PEDIDO = IP.COD_PEDIDO
INNER JOIN PRODUTO PROD
	ON IP.COD_PRODUTO = PROD.COD_PRODUTO
INNER JOIN PRODUTO_CATEGORIA PC
	ON PROD.COD_PRODUTO = PC.COD_PRODUTO
INNER JOIN CATEGORIA CAT
	ON PC.COD_CATEGORIA = CAT.COD_CATEGORIA
WHERE PROD.QUANTIDADE_DISPONIVEL = 0;
--

-- Mostra todos os produtos ordenados por categoria
SELECT C.NOME,
		C.EMAIL,
		P.VALOR_TOTAL,
		P.DESCONTO,
		IP.PRECO_UNITARIO,
		IP.VALOR,
		PROD.NOME,
		PROD.QUANTIDADE_DISPONIVEL,
		CAT.NOME
FROM CLIENTE C
INNER JOIN PEDIDO P
	ON C.COD_CLIENTE = P.COD_CLIENTE
INNER JOIN ITEM_PEDIDO IP
	ON P.COD_PEDIDO = IP.COD_PEDIDO
INNER JOIN PRODUTO PROD
	ON IP.COD_PRODUTO = PROD.COD_PRODUTO
INNER JOIN PRODUTO_CATEGORIA PC
	ON PROD.COD_PRODUTO = PC.COD_PRODUTO
INNER JOIN CATEGORIA CAT
	ON PC.COD_CATEGORIA = CAT.COD_CATEGORIA
ORDER BY CAT.NOME
--