USE COMEX;

SELECT P.NOME,
	P.DESCRICAO,
	IP.PRECO_UNITARIO,
	IP.VALOR,
	IP.TIPO_DESCONTO
FROM PRODUTO P
INNER JOIN ITEM_PEDIDO IP
	ON P.COD_PRODUTO = IP.COD_PRODUTO
--

SELECT P.NOME,
	P.DESCRICAO,
	IP.PRECO_UNITARIO,
	IP.VALOR,
	IP.TIPO_DESCONTO
FROM PRODUTO P
LEFT JOIN ITEM_PEDIDO IP
	ON P.COD_PRODUTO = IP.COD_PRODUTO
--

SELECT P.NOME,
	P.DESCRICAO,
	IP.PRECO_UNITARIO,
	IP.VALOR,
	IP.TIPO_DESCONTO
FROM PRODUTO P
RIGHT JOIN ITEM_PEDIDO IP
	ON P.COD_PRODUTO = IP.COD_PRODUTO
--

SELECT P.NOME,
	P.DESCRICAO,
	IP.PRECO_UNITARIO,
	IP.VALOR,
	IP.TIPO_DESCONTO
FROM PRODUTO P
CROSS JOIN ITEM_PEDIDO IP
	ON P.COD_PRODUTO = IP.COD_PRODUTO
--