USE COMEX;

SELECT P.NOME,
	P.PRECO_UNITARIO,
	P.QUANTIDADE_DISPONIVEL,
	C.NOME
FROM PRODUTO P
INNER JOIN PRODUTO_CATEGORIA PC
	ON P.COD_PRODUTO = PC.COD_PRODUTO
INNER JOIN CATEGORIA C
	ON PC.COD_CATEGORIA = C.COD_PRODUTO
--

SELECT P.NOME,
	P.PRECO_UNITARIO,
	P.QUANTIDADE_DISPONIVEL,
	C.NOME
FROM PRODUTO P
LEFT JOIN PRODUTO_CATEGORIA PC
	ON P.COD_PRODUTO = PC.COD_PRODUTO
LEFT JOIN CATEGORIA C
	ON PC.COD_CATEGORIA = C.COD_PRODUTO
--

SELECT P.NOME,
	P.PRECO_UNITARIO,
	P.QUANTIDADE_DISPONIVEL,
	C.NOME
FROM PRODUTO P
RIGHT JOIN PRODUTO_CATEGORIA PC
	ON P.COD_PRODUTO = PC.COD_PRODUTO
RIGHT JOIN CATEGORIA C
	ON PC.COD_CATEGORIA = C.COD_PRODUTO
--

SELECT P.NOME,
	P.PRECO_UNITARIO,
	P.QUANTIDADE_DISPONIVEL,
	C.NOME
FROM PRODUTO P
CROSS JOIN PRODUTO_CATEGORIA PC
	ON P.COD_PRODUTO = PC.COD_PRODUTO
CROSS JOIN CATEGORIA C
	ON PC.COD_CATEGORIA = C.COD_PRODUTO
--