USE COMEX;

SELECT  C.NOME,
	C.EMAIL,
	U.LOGIN
FROM CLIETE C
INNER JOIN USUARIO U
ON C.COD_CLIENTE = U.COD_CLIENTE;
--

SELECT  C.NOME,
	C.EMAIL,
	U.LOGIN
FROM CLIETE C
LEFT JOIN USUARIO U
ON C.COD_CLIENTE = U.COD_CLIENTE;
--

SELECT  C.NOME,
	C.EMAIL,
	U.LOGIN
FROM CLIETE C
RIGHT JOIN USUARIO U
ON C.COD_CLIENTE = U.COD_CLIENTE;
--

SELECT  C.NOME,
	C.EMAIL,
	U.LOGIN
FROM CLIETE C
CROSS JOIN USUARIO U
ON C.COD_CLIENTE = U.COD_CLIENTE;
--