USE COMEX;

SELECT U.NOME,
	U.EMAIL,
	P.VALOR_TOTAL,
	P.DESCONTO
FROM CLIENTE C
INNER JOIN PERFIL P
	ON U.COD_CLIENTE = P.COD_CLIENTE;
--

SELECT U.NOME,
	U.EMAIL,
	P.VALOR_TOTAL,
	P.DESCONTO
FROM CLIENTE C
LEFT JOIN PERFIL P
	ON U.COD_CLIENTE = P.COD_CLIENTE;
--

SELECT U.NOME,
	U.EMAIL,
	P.VALOR_TOTAL,
	P.DESCONTO
FROM CLIENTE C
RIGHT JOIN PERFIL P
	ON U.COD_CLIENTE = P.COD_CLIENTE;
--

SELECT U.NOME,
	U.EMAIL,
	P.VALOR_TOTAL,
	P.DESCONTO
FROM CLIENTE C
CROSS JOIN PERFIL P
	ON U.COD_CLIENTE = P.COD_CLIENTE;
--