USE COMEX;

-- Relatorio de usuarios e senhas
SELECT C.NOME,
	C.CPF,
	U.Login,
	U.SENHA	
FROM CLIENTE C
INNER JOIN USUARIO U
	ON C.COD_CLIENTE = U.COD_CLIENTE
INNER JOIN USUARIO_PERFIL UP
	ON U.COD_USUARIO = UP.COD_USUARIO
INNER JOIN PERFIL P
	ON UP.COD_PERFIL = P.COD_PERFIL;
--

-- Qauntidade de clientes por Perfil
SELECT P.NOME, 
	COUNT(C.CPF)
FROM CLIENTE C
INNER JOIN USUARIO U
	ON C.COD_CLIENTE = U.COD_CLIENTE
INNER JOIN USUARIO_PERFIL UP
	ON U.COD_USUARIO = UP.COD_USUARIO
INNER JOIN PERFIL P
	ON UP.COD_PERFIL = P.COD_PERFIL
GROUP BY P.NOME
--

-- Listar clientes sem login
SELECT C.NOME,
	C.CPF,
	U.Login
FROM CLIENTE C
INNER JOIN USUARIO U
	ON C.COD_CLIENTE = U.COD_CLIENTE
INNER JOIN USUARIO_PERFIL UP
	ON U.COD_USUARIO = UP.COD_USUARIO
INNER JOIN PERFIL P
	ON UP.COD_PERFIL = P.COD_PERFIL
WHERE U.LOGIN IS NULL;
--