USE COMEX;

-- Relatorio de todos os produtos em pedido
SELECT P.NOME,
	P.QUANTIDADE_DISPONIVEL,
	C.NOME,
	IP.PRECO_UNITARIO,
	IP.VALOR	
FROM PRODUTO P
INNER JOIN ITEM_PEDIDO IP
	ON P.COD_PRODUTO = IP.COD_PRODUTO
INNER JOIN PRODUTO_CATEGORIA PC
	ON P.COD_PRODUTO = PC.COD_PRODUTO
INNER JOIN CATEGORIA C
	ON PC.COD_CATEGORIA = C.COD_PRODUTO;
--

--Relatorio dos produtos por categoria
SELECT P.NOME,
	P.QUANTIDADE_DISPONIVEL,
	C.NOME,
	IP.PRECO_UNITARIO,
	IP.VALOR	
FROM PRODUTO P
INNER JOIN ITEM_PEDIDO IP
	ON P.COD_PRODUTO = IP.COD_PRODUTO
INNER JOIN PRODUTO_CATEGORIA PC
	ON P.COD_PRODUTO = PC.COD_PRODUTO
INNER JOIN CATEGORIA C
	ON PC.COD_CATEGORIA = C.COD_PRODUTO
ORDER BY C.NOME;
--

--Relatorio dos pedidos com valor menor que 500 unidades monetarias
SELECT P.NOME,
	P.QUANTIDADE_DISPONIVEL,
	C.NOME,
	IP.PRECO_UNITARIO,
	IP.VALOR	
FROM PRODUTO P
INNER JOIN ITEM_PEDIDO IP
	ON P.COD_PRODUTO = IP.COD_PRODUTO
INNER JOIN PRODUTO_CATEGORIA PC
	ON P.COD_PRODUTO = PC.COD_PRODUTO
INNER JOIN CATEGORIA C
	ON PC.COD_CATEGORIA = C.COD_PRODUTO
WHERE IP.PRECO_UNITARIO <= 500
ORDER BY C.NOME;
--