USE COMEX;

SELECT U.LOGIN,
	P.NOME
FROM USUARIO U
INNER JOIN USUARIO_PERFIL UP
	ON U.COD_USUARIO = UP.COD_USUARIO
INNER JOIN PERFIL P
	ON UP.COD_PERFIL = P.COD_PERFIL;
--

SELECT U.LOGIN,
	P.NOME
FROM USUARIO U
LEFT JOIN USUARIO_PERFIL UP
	ON U.COD_USUARIO = UP.COD_USUARIO
LEFT JOIN PERFIL P
	ON UP.COD_PERFIL = P.COD_PERFIL;
--

SELECT U.LOGIN,
	P.NOME
FROM USUARIO U
RIGHT JOIN USUARIO_PERFIL UP
	ON U.COD_USUARIO = UP.COD_USUARIO
RIGHT JOIN PERFIL P
	ON UP.COD_PERFIL = P.COD_PERFIL;
--

SELECT U.LOGIN,
	P.NOME
FROM USUARIO U
CROSS JOIN USUARIO_PERFIL UP
	ON U.COD_USUARIO = UP.COD_USUARIO
CROSS JOIN PERFIL P
	ON UP.COD_PERFIL = P.COD_PERFIL;
--