USE teste_comex;

SELECT c.NOME AS NOME, COUNT(c.NOME) AS QTD_PEDIDO, SUM(itdp.QUANTIDADE * itdp.PRECOUNITARIO) AS VALOR_TOTAL
FROM PEDIDO pdd
JOIN ITEMDEPEDIDO itdp
ON pdd.id = itdp.PEDIDO_id
JOIN CLIENTE c
ON pdd.CLIENTE_CPF = c.CPF
GROUP BY c.NOME
ORDER BY SUM(itdp.QUANTIDADE * itdp.PRECOUNITARIO) DESC;