USE teste_comex;

SELECT c.NOME AS NOMECAT, SUM(itdp.QUANTIDADE) AS QUANTIDADE,  SUM((itdp.QUANTIDADE * itdp.PRECOUNITARIO)) AS MONTANTE
FROM ITEMDEPEDIDO itdp
JOIN PEDIDO pdd
ON itdp.PEDIDO_id = pdd.id
JOIN PRODUTO p
ON pdd.id = p.id
JOIN CATEGORIA c
ON p.CATEGORIA_id = c.id
WHERE c.NOME = "INFORMATICA"
GROUP BY c.NOME;