USE SUCOS_VENDAS;

/**tabela nao pode ter a chave primario como NULL (anulavel)**/
ALTER TABLE [TABELA DE PRODUTOS]
ALTER COLUMN [CODIGO DO PRODUTO]
varchar(20) NOT NULL;

ALTER TABLE [TABELA DE PRODUTOS]
ADD CONSTRAINT PK_TABELA_DE_PRODUTOS
PRIMARY KEY CLUSTERED ([CODIGO DO PRODUTO])