USE SUCOS_VENDAS;

ALTER TABLE [TABELA DE CLIENTES]
ALTER COLUMN CPF
CHAR(11) NOT NULL;

ALTER TABLE [TABELA DE CLIENTES]
ADD CONSTRAINT PK_TABELA_DE_CLIENTES
PRIMARY KEY CLUSTERED ([CPF]);

