CREATE DATABASE SUCOS_VENDAS_01;

CREATE DATABASE SUCOS_VENDAS_02
ON (NAME = 'SUCOS_VENDAS.DAT',
	FILENAME = 'C:\TEMP2\SALES_VENDAS_02.MDF',
	SIZE = 10MB,
	MAXSIZE = 50MB,
	FILEGROWTH = 5MB)

LOG ON
	(NAME = 'SUCOS_VENDAS.LOG',
	FILENAME = 'C:\TEMP2\SALES_VENDAS_02.LDF',
	SIZE = 10MB,
	MAXSIZE = 50MB,
	FILEGROWTH = 5MB);


CREATE DATABASE [SUCOS_VENDAS_06]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SUCOS_VENDAS_06', FILENAME = N'C:\TEMP2\SUCOS_VENDAS_06.mdf' , SIZE = 10240KB , MAXSIZE = 25600KB , FILEGROWTH = 10240KB )
 LOG ON 
( NAME = N'SUCOS_VENDAS_06_log', FILENAME = N'C:\TEMP2\SUCOS_VENDAS_06_log.ldf' , SIZE = 10240KB , MAXSIZE = 25600KB , FILEGROWTH = 5120KB )