USE SUCOS_VENDAS;

SELECT * FROM [TABELA DE PRODUTOS] WHERE EMBALAGEM = 'PET';

SELECT * FROM [TABELA DE PRODUTOS] WHERE [PRECO DE LISTA] = 8.008;

SELECT * FROM [TABELA DE PRODUTOS] WHERE [PRECO DE LISTA] < 10;

SELECT * FROM [TABELA DE PRODUTOS] WHERE [PRECO DE LISTA] > 13.312;

SELECT * FROM [TABELA DE PRODUTOS] WHERE [PRECO DE LISTA] >= 13.312;

SELECT * FROM [TABELA DE PRODUTOS] WHERE EMBALAGEM <= 'LATA';

SELECT * FROM [TABELA DE PRODUTOS] WHERE EMBALAGEM >= 'LATA';

SELECT * FROM [TABELA DE PRODUTOS] WHERE EMBALAGEM <> 'LATA';

--

SELECT * FROM [TABELA DE CLIENTES] WHERE [DATA DE NASCIMENTO] = '1995-09-11'

SELECT * FROM [TABELA DE CLIENTES] WHERE [DATA DE NASCIMENTO] >= '1995-09-11'

SELECT * FROM [TABELA DE CLIENTES] WHERE [DATA DE NASCIMENTO] <= '1995-09-11'

SELECT * FROM [TABELA DE CLIENTES] WHERE YEAR([DATA DE NASCIMENTO]) = 1995

SELECT * FROM [TABELA DE CLIENTES] WHERE MONTH([DATA DE NASCIMENTO]) = 9

SELECT * FROM [TABELA DE CLIENTES] WHERE DAY([DATA DE NASCIMENTO]) = 12

-- Filtro composto
-- AND\OR

SELECT * FROM TABELA WHERE FILTRO ---> SO SERAO VISIVEIS RESULTADOS ONDE O FILTRO\EXPRESSAO FOR VERDADEIRO

SELECT * FROM [TABELA DE CLIENTES] WHERE DAY([DATA DE NASCIMENTO]) = 12;

SELECT * FROM [TABELA DE CLIENTES] WHERE DAY([DATA DE NASCIMENTO]) = 12 OR BAIRRO = 'Tijuca';

SELECT * FROM [TABELA DE CLIENTES] WHERE YEAR([DATA DE NASCIMENTO]) = 1995 AND SEXO = 'F';

SELECT * FROM [TABELA DE CLIENTES] WHERE YEAR([DATA DE NASCIMENTO]) = 1995 AND SEXO = 'M';