USE SUCOS_VENDAS;

INSERT INTO [TABELA DE PRODUTOS]
([CODIGO DO PRODUTO],
[NOME DO PRODUTO],
EMBALAGEM,
TAMANHO,
SABOR,
[PRECO DE LISTA])
VALUES
('1040107',
'Light - 350 ml - Melância',
'Lata',
'350 ml',
'Melancia',
4.56);

INSERT INTO [TABELA DE PRODUTOS]
([CODIGO DO PRODUTO],
[NOME DO PRODUTO],
EMBALAGEM,
TAMANHO,
SABOR,
[PRECO DE LISTA])
VALUES
('1037797',
'Clean - 2 Litros - Laranja',
'PET',
'2 Litros',
'Laranja',
16.01);

INSERT INTO [TABELA DE PRODUTOS]
([CODIGO DO PRODUTO],
[NOME DO PRODUTO],
EMBALAGEM,
TAMANHO,
SABOR,
[PRECO DE LISTA])
VALUES
('1000889',
'Sabor da Montanha - 700 ml - Uva',
'Garrafa',
'700ml',
'Uva',
6.31);

INSERT INTO [TABELA DE PRODUTOS]
VALUES
('788975','Pedaços de Frutas - 1,5 Litros - Maça',
'PET','1.5 Litros','Maça',18.01);

DELETE FROM [TABELA DE PRODUTOS]
WHERE [CODIGO DO PRODUTO] = '788975';

/** alterando ordem de inserção dos valores **/
INSERT INTO [TABELA DE PRODUTOS]
([CODIGO DO PRODUTO],[NOME DO PRODUTO],EMBALAGEM,TAMANHO,[PRECO DE LISTA],SABOR)
VALUES
('788975','Pedaços de Frutas - 1,5 Litros - Maça',
'PET','Maça',18.01,'1.5 Litros');

INSERT INTO [TABELA DE PRODUTOS]
([CODIGO DO PRODUTO],[NOME DO PRODUTO],EMBALAGEM,TAMANHO,[PRECO DE LISTA],SABOR)
VALUES
('1002767','Videira do Campo - 700ml - Cereja/Maça',
'Garrafa','700ml',8.41,'Cereja/Maca');

DELETE FROM [TABELA DE PRODUTOS]
WHERE [CODIGO DO PRODUTO] IS NULL;

