USE COMEX;

-- tabela clientes
CREATE TABLE CLIENTES
(
	COD_CLIENTE BIGINT NOT NULL PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	CPF VARCHAR(11) NOT NULL,
	TELEFONE1 VARCHAR(20),
	TELEFONE2 VARCHAR(20),
	BAIRRO VARCHAR(200) NOT NULL,
	CIDADE VARCHAR(200) NOT NULL,
);

-- tabela
CREATE TABLE CATEGORIA
(
	COD_CATEGORIA BIGINT NOT NULL PRIMARY KEY,
	NOME VARCHAR(200) NOT NULL,
	DESCRICAO VARCHAR(200),
);

-- tabela perfil
CREATE TABLE PERFIL
(
	COD_PERFIL BIGINT NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	DESCRICAO VARCHAR(255),
	PRIMARY KEY(COD_PERFIL),
);

-- tabela produto
CREATE TABLE PRODUTO
(
	COD_PRODUTO BIGINT NOT NULL,
	NOME VARCHAR(500) NOT NULL,
	DESCRICAO VARCHAR(255) NOT NULL,
	PRECO_UNITARIO MONEY NOT NULL,
	QUANTIDADE_DISPONIVEL INT NOT NULL,
	PRIMARY KEY(COD_PRODUTO),
);

-- tabela usuarios
CREATE TABLE USUARIOS
(
	COD_USUARIO BIGINT NOT NULL,
	COD_CLIENTE BIGINT NOT NULL REFERENCES CLIENTES,
	LOGIN_USUARIO VARCHAR(50) NOT NULL,
	LOGIN_SENHA VARCHAR(50) NOT NULL,
	PRIMARY KEY(COD_USUARIO),
);

-- tabela usuarios_perfis
--cria chave composta(ao mesmo tempo fk e pk)
CREATE TABLE USUARIOS_PERFIS
(
	COD_USUARIO BIGINT NOT NULL REFERENCES USUARIOS,
	COD_PERFIL BIGINT NOT NULL REFERENCES PERFIS,
	PRIMARY KEY(COD_USUARIO, COD_PERFIL),
);

-- tabela pedidos
CREATE TABLE PEDIDOS
(
	COD_PEDIDO BIGINT NOT NULL PRIMARY KEY,
	COD_CLIENTE BIGINT NOT NULL REFERENCES CLIENTES,
	VALOR_TOTAL MONEY NOT NULL,
	DESCONTO MONEY NOT NULL,
);

-- tabela itens_pedidos
CREATE TABLE ITENS_PEDIDOS
(
	COD_PEDIDO BIGINT NOT NULL REFERENCES PEDIDOS,
	COD_PRODUTO BIGINT NOT NULL REFERENCES PRODUTOS,
	PRECO_UNITARIO MONEY,
	DESCONTO MONEY NOT NULL,
	TIPO_DESCONTO VARCHAR(50),
	VALOR MONEY,
	PRIMARY KEY(COD_PEDIDO, COD_PRODUTO),
);

-- tabela produtos_categorias
CREATE TABLE PRODUTOS_CATEGORIAS
(
	COD_PEDIDO BIGINT NOT NULL REFERENCES PEDIDOS,
	COD_PRODUTO BIGINT NOT NULL REFERENCES PRODUTOS,
	PRIMARY KEY(COD_PEDIDO, COD_PRODUTO),
);