CREATE DATABASE COMEX
ON (NAME = 'COMEX.dat',
	FILENAME = 'C:\semana_15\COMEX.mdf',
	SIZE = 5MB,
	MAXSIZE = 100MB,
	FILEGROWTH = 5)
LOG ON
	(NAME = 'COMEX.log',
	FILENAME = 'C:\semana_15\COMEX.ldf',
	SIZE = 5MB,
	MAXSIZE = 100MB,
	FILEGROWTH = 5);