USE COMEX;

/**
CREATE TABLE [dbo].[CATEGORIA](
	[COD_CATEGORIA] [bigint] NOT NULL,
	[NOME] [varchar](200) NOT NULL,
	[DESCRICAO] [varchar](200) NULL,
PRIMARY KEY CLUSTERED 
(
	[COD_CATEGORIA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
**/

INSERT INTO CATEGORIA
	VALUES
		(6666, 'LIVROS', 'LITERATURA DIVERSA'),
		(7777, 'ELETRODOMESTICOS', 'LINHA BRANCA'),
		(8888, 'INFORMATICA', 'EQUIPAMENTOS TI');

SELECT * FROM CATEGORIA;

SELECT NOME FROM CATEGORIA;

SELECT NOME FROM CATEGORIA ORDER BY NOME;

UPDATE CATEGORIA SET DESCRICAO = 'EQUIPAMENTOS DE INFORMATICA' WHERE COD_CATEGORIA = 8888;

SELECT * FROM CATEGORIA;

DELETE FROM CATEGORIA WHERE COD_CATEGORIA = 8888;

SELECT * FROM CATEGORIA;

INSERT INTO CATEGORIA VALUES (8888, 'INFORMATICA', 'EQUIPAMENTOS TI');

SELECT * FROM CATEGORIA;