USE COMEX;

/**
CREATE TABLE [dbo].[PERFIL](
	[COD_PERFIL] [bigint] NOT NULL,
	[NOME] [varchar](100) NOT NULL,
	[DESCRICAO] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[COD_PERFIL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
**/

INSERT INTO PERFIL
	VALUES
	(111, 'ADMIN', 'ADMINISTRADOR'),
	(222, 'Estoquista', 'Estoquista'),
	(333, 'Cliente', 'Cliente Comum');

SELECT * FROM PERFIL

SELECT NOME FROM PERFIL;

SELECT NOME FROM PERFIL ORDER BY NOME;

UPDATE PERFIL SET DESCRICAO = 'CLIENTES COMUNS' WHERE COD_PERFIL = 333;

SELECT * FROM PERFIL

DELETE FROM PERFIL WHERE COD_PERFIL = 333;

SELECT * FROM PERFIL

INSERT INTO PERFIL VALUES (333, 'Cliente', 'Cliente Comum');

SELECT * FROM PERFIL