USE COMEX;

/**
CREATE TABLE [dbo].[PRODUTOS_CATEGORIAS](
	[COD_PEDIDO] [bigint] NOT NULL,
	[COD_PRODUTO] [bigint] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[COD_PEDIDO] ASC,
	[COD_PRODUTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PRODUTOS_CATEGORIAS]  WITH CHECK ADD FOREIGN KEY([COD_PEDIDO])
REFERENCES [dbo].[PEDIDOS] ([COD_PEDIDO])
GO

ALTER TABLE [dbo].[PRODUTOS_CATEGORIAS]  WITH CHECK ADD FOREIGN KEY([COD_PRODUTO])
REFERENCES [dbo].[PRODUTO] ([COD_PRODUTO])
GO
**/

INSERT INTO PRODUTOS_CATEGORIAS
	VALUES
		(1000000000001, 000000000001),
		(2000000000002, 000000000002),
		(3000000000003, 000000000003);

SELECT * FROM PRODUTOS_CATEGORIAS;