USE COMEX;

/**
CREATE TABLE [dbo].[USUARIOS](
	[COD_USUARIO] [bigint] NOT NULL,
	[COD_CLIENTE] [bigint] NOT NULL,
	[LOGIN_USUARIO] [varchar](50) NOT NULL,
	[LOGIN_SENHA] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[COD_USUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[USUARIOS]  WITH CHECK ADD FOREIGN KEY([COD_CLIENTE])
REFERENCES [dbo].[CLIENTES] ([COD_CLIENTE])
GO
**/

INSERT INTO USUARIOS
	VALUES
		(0000, 111111, 'aaaaauser', 'aaaaasenha'),
		(1111, 222222, 'bbbbbuser', 'bbbbbsenha'),
		(2222, 333333, 'cccccuser', 'cccccsenha');

SELECT * FROM USUARIOS;

SELECT LOGIN_USUARIO FROM USUARIOS;

 -- DEU ERRO SELECT LOGIN_USUARIO FROM USUARIOS ORDER BY NOME;

UPDATE USUARIOS SET COD_USUARIO = 0000 WHERE COD_CLIENTE = 111111;

SELECT * FROM USUARIOS;

DELETE FROM USUARIOS WHERE COD_USUARIO = 0000;

SELECT * FROM USUARIOS;

INSERT INTO USUARIOS VALUES (0000, 111111, 'aaaaauser', 'aaaaasenha');

SELECT * FROM USUARIOS;